apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: go-survey
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db-app
  replicas: 1
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
        - name: mongo-app
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc